# config/packages/easy_admin.yaml
easy_admin:
    translation_domain: 'form'
    entities:
        User:
            class: App\Entity\User
            list: 
                fields: 
                    - { property: 'name', label: 'label.Name' }
                
            
        Appointement:
            class: App\Entity\Appointement
